# -*- coding: utf-8 -*-
"""dictionaries

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4yf_CSuriYTfkWTCsKAvm1rIrg68Ma9
"""

#Q1

loop = int(input("Enter how many items you want to add to your dictionary:"))
dic = {}
for i in range(loop):
  product = input("enter the product name:").lower() 
  price = int(input("enter the price of the product:"))
  dic[product] = price
exist = True
while exist:
  while True:

    out_product =  input("enter the product name you want:").lower() 
    if out_product in dic:
      print("Price of ",out_product," is ",dic[out_product])
      break
    else :
      print("The product does not exist in Dictionary")  
      break
  repeat = input("want more product yes / no").lower() 
  if repeat == 'yes':
    continue
  else :
    break

#Q2

loop = int(input("Enter how many items you want to add to your dictionary:"))
dic = {}
for i in range(loop):
  product = input("enter the product name:").lower() 
  price = int(input("enter the price of the product:"))
  dic[product] = price
dollar = int(input("enter the amount:"))  
for key ,values in dic.items():
  if int(values)<dollar :
    print(key)

#Q3

my_dic = {'january':31, 'february':28, 'march':31, 'april':30,
'may':31, 'june':30, 'july':31, 'august':31,
'september':30, 'october':31, 'november':30, 'december':31}

# part a
month = input("Enter the name of month :").lower()
print("The number of days in ",month,' are ',my_dic[month])

#part b
print(sorted(my_dic))

#part c
for key ,values in my_dic.items():
  if int(values)==31:
    print(key)

#part d
#ofc not ez

#Q4

# time :(